### PR TITLE
fixed how handling of disconnect was implemented 

### PR DESCRIPTION
**Pull request by alir128**
only rtc connection state is now being monitored for changes.

@Lakshya2610 backend and client should be updated to reflect these changes.

#100

### CODE REVIEW

**Comment by Lakshya2610** [comment]
> only rtc connection state is now being monitored for changes.
> 
> @Lakshya2610 backend and client should be updated to reflect these changes.
> 
> #100

@alir128 Seems like you already made the changes for the client for this? As for backend, I'll make the changes

**Comment by alir128** [comment]
> > only rtc connection state is now being monitored for changes.
> > @Lakshya2610 backend and client should be updated to reflect these changes.
> > #100
> 
> @alir128 Seems like you already made the changes for the client for this? As for backend, I'll make the changes

By Client I meant the web app wouldn't that need to be updated to reflect the changes. I removed the socket logoff emit.

**Comment by Lakshya2610** [comment]
> > > only rtc connection state is now being monitored for changes.
> > > @Lakshya2610 backend and client should be updated to reflect these changes.
> > > #100
> > 
> > 
> > @alir128 Seems like you already made the changes for the client for this? As for backend, I'll make the changes
> 
> By Client I meant the web app wouldn't that need to be updated to reflect the changes. I removed the socket logoff emit.

I'll update the web app

**Comment by alir128** [comment]
> Seems you haven't merged master into this branch which is causing the state issue. Otherwise the peer count works as expected

Yea I noticed that but it shouldn't the file changes are quite small for the extension side anyways.

**Pull request merged**
